In [9]:
# COURSE 5 - IMPORTINGG DATA FROM DIFFERENT SOURCES :

    # 1) Plain Text Files *.txt
        
        # 1.1) open() and close() function
        # 1.2) with context manager and open()
        # 1.3)  read() and readline() methods on opened file
    
    #2) FLAT FILES - *txt and *csvs
        # 2.1) Introduction 
        # 2.2) Using Numpy Arrays - import only numeric data and sometimes mixted type data (structured numpy array) 
#-next- # 2.3) Using Padas -- to import into dataframes
        
    # 2) Native to other softwares - suhc as excel, SAS and MATLAB files
    # 3) Relational Databases - SQL, My SQL
    


In [10]:
# 1) Plain *txt files

# This could be plain text files like a novel page 
# something containing table data  -- this is know as FLAT FILES


        ## 1.1) READING A PLAIN TEXT FILE - using open() function -- require close() function at the end
    
filename = "random_text.txt"  #<-- needs to be current working directory

file = open(filename, mode = 'r') # r is read only mode

text = file.read() #<-- applying the method read() to read the entire text file

file.close() #<-- close the connection to the file

print(text)

print(file.closed) #<-- # Check whether file is closed

just created this file for fun
second line - learning python
True


In [11]:
        ## 1.2) READING A PLAIN TEXT FILE - using context manager with and open() function - dosen't require close()
    
# Context manager with allows you to create a context in which we can execute commands with the file open

filename = "random_text.txt"

with open(filename, mode = 'r') as file:
    print(file.read())

# <-- file closed automatically outside the context of the with clause
# <-- What we are doing here is binding a variable in the context manager construct 
# .. while still within this construct the variable file will be bound to open filenmae in read mode

just created this file for fun
second line - learning python


In [12]:
    ## Accessing file in other working directory using above same comman
    
import os # <-- package to work with files and connections in the operating system

os.getcwd() #<-- gets current working directory

'D:\\Data Camp\\Files\\Course5'

In [13]:
os.chdir("D:\Data Camp\Files\Course5") #<-- changes the current working directory

In [14]:
     ## 1.3) read() and readline() Methods to read : 
                                #) entire texst file - read()
                                #) read line by line - readline()

filename = "moby_dick.txt"

with open(filename, mode = 'r') as file:
    print(file.read()) # <-- read() imports the entire file


CHAPTER 1. Loomings.

Call me Ishmael. Some years ago--never mind how long precisely--having
little or no money in my purse, and nothing particular to interest me on
shore, I thought I would sail about a little and see the watery part of
the world. It is a way I have of driving off the spleen and regulating
the circulation. Whenever I find myself growing grim about the mouth;
whenever it is a damp, drizzly November in my soul; whenever I find
myself involuntarily pausing before coffin warehouses, and bringing up
the rear of every funeral I meet; and especially whenever my hypos get
such an upper hand of me, that it requires a strong moral principle to
prevent me from deliberately stepping into the street, and methodically
knocking people's hats off--then, I account it high time to get to sea
as soon as I can. This is my substitute for pistol and ball. With a
philosophical flourish Cato throws himself upon his sword; I quietly
take to the ship. There is nothing surprising in this. If th

In [ ]:
# Read & print the first 3 lines

with open('moby_dick.txt') as file:
    print(file.readline()) #<-- readline() reads one line 
    print(file.readline())
    print(file.readline())

In [ ]:
    #2) FLAT FILES 
    
        #2.1) INTRODUCTION TO FLAT FILES
         
            # Flat files are basic text files containing records, that is table data without structured relationships
         # This is in contrast to relational databases, in which coloumns of different tables can be related
         # More generically flat files consist of : 
            # Records : A record in a flat file is composed of fields or attributes, each of which contains at most one item of information. Ex : name of persons
            # Coloumn : contians feature or attributes. Ex: age, complexity, height of the persons
            # Header : could be present. It's the firt row, describing the contents of the data coloumns or states of what the corresponding coloumns and there featured attrubtes are. Ex. Age, weight, etc coloumn names
         # File Extension :  
            # *csv - Comma Separated Values -- values in each row (records) are separated in comma 
            # *txt -- text file
         # Delimiter : Values in flat files can be separated by various characters called delimiters. ex comma (','), tabs ('\t')
        
        
        ## How do you import flat files?
            # Two important packages - NumPy, Pandas
            # Numpy - If a file consists entirely of numbers and we want to store as Numpy arrays
            # Pandas - when we want to store data into a dataframe

In [23]:
      # 2.2) Importing Flat files with only numeric data (or simple mixed datatype) using Numpy
    
# Example MNIST.txt which is comma delimited and importing it as an Numpy Array
# Why Numpy Array : 
    # Numpy arrays are python's standard for storing numerical data
    # Numpy arrays are also essential for other packages such as Sci-Kit learn (used for machine learning)
    # Consists of various Numpy functions to load data efficiently into Numpy arryas. Example :
        # np.loadtxt() -
            # -- great for simple importing where data type is not mixed
            # -- arguments : filename, delimiter, skiprows, usecols, dtype and many other arguments
            
        # np.genfromtxt() -
            # -- can handle mixed data types. 
            # -- If we pass dtype=None to it, it will figure out what types each column should be.
            # -- results in a structured array :  1D array, where each element of the array is a row of the flat file imported
        
        # np.recfromcsv()
            # -- same as np.genfromtxt() except its default dtype = None
        
        
#importing file as numpy array using loadtxt()

import numpy as np

filename = 'data2.csv'
 
data = np.loadtxt(filename, delimiter = ',', skiprows = 1)  #< -- specify the delimter type. By defaults it is blank space
                                                            #< -- skiprows = 1; skips the first row which is string data
print(data)

[[  1.   2.   4.  16.]
 [  2.   4.   5.  25.]
 [  3.   6.   7.  49.]
 [  4.   8.   1.   1.]
 [  5.  10.   3.   9.]
 [  6.  12.   5.  25.]
 [  7.  14.   6.  36.]
 [  8.  16.   7.  49.]
 [  9.  18.   8.  64.]
 [ 10.  20.   9.  81.]
 [ 11.  22.  10. 100.]
 [ 12.  24.  11. 121.]
 [ 13.  26.  12. 144.]
 [ 14.  28.  13. 169.]
 [ 15.  30.  14. 196.]
 [ 16.  32.  15. 225.]
 [ 17.  34.  16. 256.]
 [ 18.  36.  17. 289.]
 [ 19.  38.  18. 324.]
 [ 20.  40.  19. 361.]]


In [25]:
#to extract just the 3 and 4th coloumn
data = np.loadtxt(filename, delimiter = ',', skiprows = 1, usecols = [2,3]) #<-- extract only 3rd and 4th coloumns

#< -- usecols = [] passes the list containing the ints for the index of  coloumns to be extracted 
print(data)

[[  4.  16.]
 [  5.  25.]
 [  7.  49.]
 [  1.   1.]
 [  3.   9.]
 [  5.  25.]
 [  6.  36.]
 [  7.  49.]
 [  8.  64.]
 [  9.  81.]
 [ 10. 100.]
 [ 11. 121.]
 [ 12. 144.]
 [ 13. 169.]
 [ 14. 196.]
 [ 15. 225.]
 [ 16. 256.]
 [ 17. 289.]
 [ 18. 324.]
 [ 19. 361.]]


In [26]:
# we can also the specify the data type in which we want to import the data

data = np.loadtxt(filename, delimiter = ',', skiprows = 1, usecols = [2,3], dtype = str) 
#<-- extract 3rd and 4th coloumns as strings

#< -- usecols = [] passes the list containing the ints for the index of  coloumns to be extracted 
print(data)

[['4' '16']
 ['5' '25']
 ['7' '49']
 ['1' '1']
 ['3' '9']
 ['5' '25']
 ['6' '36']
 ['7' '49']
 ['8' '64']
 ['9' '81']
 ['10' '100']
 ['11' '121']
 ['12' '144']
 ['13' '169']
 ['14' '196']
 ['15' '225']
 ['16' '256']
 ['17' '289']
 ['18' '324']
 ['19' '361']]


In [40]:
# to handle mixed dataypes we used np.genfrmtxt()

data = np.genfromtxt('titanic_sub.csv', delimiter=',', names=True, dtype=None)

# Here, the first argument is the filename, 
# the second specifies the delimiter , 
# names = True -- tells us there is a header. 
# Because the data are of different types, data is an object called a structured array. 
# Because numpy arrays have to contain elements that are all the same type, the structured array solves this by being a 1D array,
#.. where each element of the array is a row of the flat file imported. You can test this by checking out the array's shape in 
#.. the shell by executing np.shape(data)


print(np.shape(data)) #<-- checks the the structured array data type
print(type(data)) # <-- type of output from such mixed type files via genfromtxt()
print(data)



(891,)
<class 'numpy.ndarray'>
[(  1, 0, 3, b'male', 22.  , 1, 0, b'A/5 21171',   7.25  , b'', b'S')
 (  2, 1, 1, b'female', 38.  , 1, 0, b'PC 17599',  71.2833, b'C85', b'C')
 (  3, 1, 3, b'female', 26.  , 0, 0, b'STON/O2. 3101282',   7.925 , b'', b'S')
 (  4, 1, 1, b'female', 35.  , 1, 0, b'113803',  53.1   , b'C123', b'S')
 (  5, 0, 3, b'male', 35.  , 0, 0, b'373450',   8.05  , b'', b'S')
 (  6, 0, 3, b'male',   nan, 0, 0, b'330877',   8.4583, b'', b'Q')
 (  7, 0, 1, b'male', 54.  , 0, 0, b'17463',  51.8625, b'E46', b'S')
 (  8, 0, 3, b'male',  2.  , 3, 1, b'349909',  21.075 , b'', b'S')
 (  9, 1, 3, b'female', 27.  , 0, 2, b'347742',  11.1333, b'', b'S')
 ( 10, 1, 2, b'female', 14.  , 1, 0, b'237736',  30.0708, b'', b'C')
 ( 11, 1, 3, b'female',  4.  , 1, 1, b'PP 9549',  16.7   , b'G6', b'S')
 ( 12, 1, 1, b'female', 58.  , 0, 0, b'113783',  26.55  , b'C103', b'S')
 ( 13, 0, 3, b'male', 20.  , 0, 0, b'A/5. 2151',   8.05  , b'', b'S')
 ( 14, 0, 3, b'male', 39.  , 1, 5, b'347082',  31.

C:\Users\shobh\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  This is separate from the ipykernel package so we can avoid doing imports until


In [41]:
# Accessing rows and columns of structured arrays is super-intuitive: 
# to get the ith row, merely execute data[i] and to get the column with name 'Fare', execute data['Fare']

print(data['Survived']) #<-- only getting the survived coloumn from the structured numpy array data 

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

In [44]:
# to handle mixed dataypes we can also use  np.recfromcsv()

# Assign the filename: file
file = 'titanic_sub.csv'

# Import file using np.recfromcsv: d
d = np.recfromcsv(file)

# Print out first three entries of d
print(d[:3])

[(1, 0, 3, b'male', 22., 1, 0, b'A/5 21171',  7.25  , b'', b'S')
 (2, 1, 1, b'female', 38., 1, 0, b'PC 17599', 71.2833, b'C85', b'C')
 (3, 1, 3, b'female', 26., 0, 0, b'STON/O2. 3101282',  7.925 , b'', b'S')]


C:\Users\shobh\Anaconda3\lib\site-packages\numpy\lib\npyio.py:2258: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  output = genfromtxt(fname, **kwargs)
