In [1]:
#Functions are pieces of reusable code that solves particular tasks. 
#We have used type() and print() functions before 
# str(), int(), bool() and float() are also functions we know to switch between data types.

#lets see some common functions usde on below list

list1 = [2.2, 3.4, 5.67, 7, 8, 1.5, 9.0, 40, 111, 0.5]

# max () -- returns the max value 
a = max(list1)
print("the max value in list1 is " + str(a))

# round() --- takes 2 input, one is the number being round and second input to number of decimal places to round to. By defaults will round to integer.
print("5.67 which is the 3rd element in list1 can be rounded to " + str(round(list1[2],1))) #Rounding 5.67 to 1 decimal place and printing it


# help() -- at any moment this can be called in to give help on any function. Example check for documentation on round. 
help(round)
#this shows the roun() funciton has two arguments number and ndigits, with the ndigits being optional argument.

#len() to get the number of elements in the list
print("the list1 has "+str(len(list1))+" elements")






the max value in list1 is 111
5.67 which is the 3rd element in list1 can be rounded to 5.7
Help on built-in function round in module builtins:

round(...)
    round(number[, ndigits]) -> number
    
    Round a number to a given precision in decimal digits (default 0 digits).
    This returns an int when called with one argument, otherwise the
    same type as the number. ndigits may be negative.

the list1 has 10 elements


In [2]:
#Multiple Arguments functions. Ex. sorted(iterabe, key = None, reverse = False)

#Sort the final list in descending order

help(sorted)

# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second
print(full)

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse=True)

# Print out full_sorted
print(full_sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.

[11.25, 18.0, 20.0, 10.75, 9.5]
[20.0, 18.0, 11.25, 10.75, 9.5]


In [5]:
# OBJECTS - So far we have learned about different variables which are all actauly objects in python

height = ['shobhit', 1.2, 'gomti', 2.4, 'arvind', 5.6]
value = 1.7
sister = 'pragya'

# all of thesea are objects with type list, float ana string respectively.
#these Objects along with type come with a bunch of METHODS.

# METHODS : These are functions that belong to a certain python object

#For example we need to get the index of 'gomti' in the list. We can apply the method to the list object height.

# syntax for using method on object : object.method()


index_of_gomti = height.index('gomti') #there we called the method index() on height to find the index of 'gomti'
print(index_of_gomti)

#Similarly call method count() on height to find how many times something appears in the list.
print(height.count(1.2)) #1.2 occurs one time, so the answer should be 1




2
1


In [10]:
#Methods are applicable for other object types too, including int, float, bool and string 

#Example of Methods for strings. 

# string.capitalize(), 

string1 = "mom"

print(string1.capitalize()) #capitalizes and returns the string

# string.replace('','') this replaces the former  part of string with later

string2 = 'Liz'
new_string2 = string2.replace("z", "sa")
print("Liz changes to " + new_string2)



Mom
Liz changes to Lisa


In [11]:
### Everything in python is an OBJECT
### Every object has associated METHODS depending onits type

## Objects with different types can have methods with same name. Example object.index()

string  = "Mommy"
list1 = [1,2,3,4,5,6]

print(string.index('o'))  #returns the index of the letter o in the string Mommy
print(list1.index(5)) #returns the index of 5 in the list1

#thus depending on the type of the object Methods behave differently

1
4


In [14]:
### Some METHODS can CHANGE THE OBJECT they are called on. 

#Example consider the append() method applied on the list2. Though it dosent generate output. It adds the element to the list2

list2 = ['a','b','c']
list2.append('d') #can add only one element at the end

print(list2)

['a', 'b', 'c', 'd']


In [ ]:
# PACKAGES are directory on python scripts. 
#Each packages are made up of MODULES
#Each MODULE is is made up of function, methods and types

#Many packages are available on python. Some popoluar are
#Numpy -- to efficiently work with arrays
#Matplotlib -- for data visualtion
#Sci-Kit Learn -- for machine learning

#Packages need to be installed on the system, and we need to use code in the script to use these packages

#To install package on one's own system, we need to use pip

#Step 1:  Donwload : get-pip.py 
#Step 2 : Go to terminal and type command : python3 get-pip.py ; this will allow us to use pip to install the python package we are choosing
#Step 3: To install numpy as exampl; command :  pip3 install numpy

#Now that the package is installed, we can now start using ti after importing it.

#To use a python package, first import it or specific moldule of python package
# IMPORTING Package in script command : import numpy

In [16]:
# A commonly used fucntion in numpy is array, which takes list as an input. However directly calling it will give an error 

array([1,2,3])

NameError: name 'array' is not defined

In [19]:
#Thus we need to call it via numpy

import numpy
numpy.array([1,2,3])

array([1, 2, 3])

In [20]:
#using the numpy.   to refer to the package can be tideous, so we can import it smartly to call it more eficiently in a script

import numpy as np
np.array([5,6,7])

array([5, 6, 7])

In [21]:
#Sometime we want to use only a specific function of a package. 
#for example we just want to use array funcitonf from numpy.
#then we can import this as follows, which allows you to simply call the array function directly in the script without numpy.()
# usually this is not an efficietn method, as can be confusing in a long script

from numpy import array 
array([7,8,9])

array([7, 8, 9])

In [22]:
# Example of using pi from MATH package for area and circumference calculation 

# Definition of radius
r = 0.43
import math as m
# Import the math package


# Calculate C
C = 2*m.pi*r

# Calculate A
A = m.pi*r**2

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [23]:
#Importing from SUBPACKAGES

#There are several ways to import packages and modules into Python. 
#Depending on the import call, you'll have to use different Python code.
# Suppose you want to use the function inv(), which is in the linalg subpackage of the scipy package. This inverts the array. 
#You want to be able to use this function as follows directly into the script my_inv([[1,2], [3,4]])

from scipy.linalg import inv as my_inv
my_inv([[1,2], [3,4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])