In [1]:
## Numpy that is numeric python amongst others providesan alternative to the regular python lists : Numpy Array

# NUmpy Arrays are similar to lists, but unlike lists calculations can be performed on entire arrays

import numpy as np

#Lets create numpy arrays from the following ists
height = [2.7, 3.1, 2.7, 1.6, 1.8]
weight= [54, 68, 78, 91, 37]

#If we just multiply the lists it wont work for bmi
bmi = weight/ height **2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [2]:
#however using numpy arrays this can be done

np_height = np.array(height) #using height list to createt the numpy array np_weight
np_weight = np.array(weight) #using height list to createt the numpy array np_height

bmi = np_weight/np_height ** 2 # this does it perfectly element wise
print(bmi)
print(' bmi is of ' + str(type(bmi)) + 'type')

[ 7.40740741  7.07596254 10.69958848 35.546875   11.41975309]
 bmi is of <class 'numpy.ndarray'>type


In [3]:
#NUmpy remarks : 

# -- Numpy can do al of these calculations imply because it assumes your numpy array can only contain values of single type (ex all float, or all bolean etc)
# -- if we try to create a numpy array with different data type it just converts all elements to string to get a string numpy array
# --  Numpy array is a new type of python type, ie floats, strings, int, bool, lists

np_array1 = np.array([1, 2.3, True, 'love'])
print(np_array1)  #look how all differnet data tpe elements are converted to strings

['1' '2.3' 'True' 'love']


In [4]:
# -- Since numpy array is itself a data type in python, it comes with its own methods which behave specifically for it.

#Consider how + acts different on list and numpy array

list1 = [1,2,3,4]
list2 = [5,6,7,8]
np_list1 = np.array(list1)
np_list2 = np.array(list2)


list3 = list1+ list2
list4  = np_list1 + np_list2

print('This is the result of adding list1 and list2 normally as lists :' + str(list3))
print('This is the result of adding list1 and list2 as numpy arrays :' + str(list4))

This is the result of adding list1 and list2 normally as lists :[1, 2, 3, 4, 5, 6, 7, 8]
This is the result of adding list1 and list2 as numpy arrays :[ 6  8 10 12]


In [5]:
##Subsetting Numpy Arrays is simar to lists 

#lets call 1st element of bmi from above

print(bmi[0])


7.4074074074074066


In [6]:
#There is another way of doing subsetting in Numpy array, using the array of BOOLEANS

#Say we want to get all the bmi values in above bmi numpy array with values greater than 10, we can do this easily.

bmi>10

array([False, False,  True,  True,  True])

In [7]:
#we can next subset the bmi this way, to show only the elements in bmi with values greaer than 10
bmi[bmi>10]

array([10.69958848, 35.546875  , 11.41975309])

In [8]:
## Nmupy are of datay type nmupy.ndarray which means its from numpy package and is a n-dimensional array

#Above examples were 1d numpy arrays, lets create 2D Numpy Arrays : np.array([ , ]) that is rows are separated by commas.
# Note ay nmupy array with any  dimension should have all its elements with single data type

#lets call out the hieght and weight list and convert it to one array that is np_2D

height = [2.7, 3.1, 2.7, 1.6, 1.8]
weight= [54, 68, 78, 91, 37]

np_2D = np.array([height, weight]) #directly using lists
np_2D1 = np.array([[2.7, 3.1, 2.7, 1.6, 1.8], [54, 68, 78, 91, 37]]) #same thing

print(np_2D)
print(np_2D1)

#We can see this has a rectangular data structrue, where each sublist in a list correpsonds to 2D row in a 2D numpy array1

print(np_2D.shape) #We can get the dimension of the 2D array, using .shape attribute. Here it give (2,5) which is 2 rows and 5 coloumns

#Subsettin og 2D numpy array; suppose we want to get element from 1st row and 3rd coloumn. Can be done two ways.
print(np_2D[0][2])
print(np_2D[0,2]) #another way of subsetting 2D numpy array

#Suppose we want elements in 2nd and 3rd coloumn from all rows
np_2D[:, 1:3]

[[ 2.7  3.1  2.7  1.6  1.8]
 [54.  68.  78.  91.  37. ]]
[[ 2.7  3.1  2.7  1.6  1.8]
 [54.  68.  78.  91.  37. ]]
(2, 5)
2.7
2.7


array([[ 3.1,  2.7],
       [68. , 78. ]])

In [9]:
#See how numpy arrays can be operated upon

np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
print(np_mat)
print(np_mat * 2) #Multiplies each element with 2; all 9 elements
print(np_mat + np.array([10, 10])) #No of coloumns should be same, adds the corresponding coloums elements to each row
print(np_mat + np_mat) #Adds each equivalent position elements

[[1 2]
 [3 4]
 [5 6]]
[[ 2  4]
 [ 6  8]
 [10 12]]
[[11 12]
 [13 14]
 [15 16]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [14]:
## Numpy - BASIC STATISTICS

#Numpy is performing statitsics operations on all of the data in the array at once for big data 

#Example numpy mean function

np_mat2 = np.array([[5, 5],
                   [4, 4],
                   [6, 6]])

print(np.mean(np_mat2)) #find mean value of all elements in np_mat ; since mean function is from nupy package, it starts with np.mean()
print(np.mean(np_mat2[:,1])) #find mean value of all elements in 2nd coloumn of np_mat
print(np.std(np_mat2)) #find standard deviation
print(np.corrcoef(np_mat2[:,0],np_mat[:,1]))  #find correlation if any between 1st and 2nd coloumn


5.0
5.0
0.816496580927726
[[1.  0.5]
 [0.5 1. ]]


In [18]:
# Numy can GENERATE DATA using random numbers

# Syntax is np.random.normal(distribution mean, distribution standard deviaion, no of samples)
#Addtionally we can round the numbers to 2 decimal places using np.round (  , no of digits to round)

np_random1 = np.round(np.random.normal(2.4, 0.5, 6), 2)
np_random2 = np.round(np.random.normal(5.6, 0.5, 6), 2)

print(np_random1)
print(np_random2)

# We can then stack these arrays as two coloumns usign np.coloumn_stack
np_stack = np.column_stack((np_random1, np_random2))
print(np_stack)

[0.98 2.7  3.09 2.88 2.43 2.96]
[6.39 6.83 5.01 6.   5.11 4.97]
[[0.98 6.39]
 [2.7  6.83]
 [3.09 5.01]
 [2.88 6.  ]
 [2.43 5.11]
 [2.96 4.97]]
